packages=eu.baltrad.dex.log
status=warn

appender.console.name=CONSOLE
appender.console.type=Console
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%d{dd MMM yyyy HH:mm:ss} %-5p %c - %m%n

appender.db.name=DB
appender.db.type=DBLogAppender

rootLogger.level=info
rootLogger.appenderRef.console.ref=CONSOLE

logger.baltrad.name=eu.baltrad
logger.baltrad.level=info

# Uncomment to debug Spring
#logger.spring.name=org.springframework
#logger.spring.level=debug

# Silence sshj - it drowns the log otherwise
logger.schmizzverification.name=net.schmizz.sshj.transport.verification
logger.schmizzverification.level=fatal
logger.schmizzsshj.name=net.schmizz.sshj
logger.schmizzsshj.level=warn
logger.schmizzsshjconnection.name=net.schmizz.sshj.connection.channel.direct.SessionChannel
logger.schmizzsshjconnection.level=info

logger.DEX.name=DEX
logger.DEX.level=info
logger.DEX.additivity=false
logger.DEX.appenderRef.console.ref=CONSOLE
logger.DEX.appenderRef.db.ref=DB

logger.BEAST.name=BEAST
logger.BEAST.level=info
logger.BEAST.additivity=false
logger.BEAST.appenderRef.db.ref=DB

logger.PGF.name=PGF
logger.PGF.level=info
logger.PGF.additivity=false
logger.PGF.appenderRef.db.ref=DB
